version: '3.1'

services:
  server:
    container_name: vitrine-server
    build:
      context: .
      args:
        vitrine_key: ${VITRINE_KEY}
    ports:
      - 80:8000
    volumes:
      - .:/opt/app
    env_file:
      - ./database.env
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${VITRINE_KEY}
      FLASK_ENV: development

  db:
    container_name: vitrine-db
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./database.env
    environment:
      MYSQL_ROOT_PASSWORD: ${VITRINE_KEY}
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    container_name: vitrine-adminer
    image: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  db_data:
    driver: local
