version: '3.1'

services:
  server:
    container_name: vitrine-server
    build:
      context: .
    ports:
      - 80:8000
    volumes:
      - .:/opt/app
    env_file:
      - .env
    environment:
      MYSQL_HOST: database
      FLASK_ENV: development

  database:
    container_name: vitrine-db
    image: mysql:5.6
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    container_name: vitrine-adminer
    image: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  db-data:
    driver: local
